---
twcc_credential: "~/.twcc_data/credential"
allow_http_cidr: 0.0.0.0/0 # NOTE: keep this will be DANGEROUS!! http protocol is not suggested!
twcc_key: tempkey
twcc_key_path: ./tempkey.pem
ansible_ssh_private_key_file: ./tempkey.pem
twcc_webserver_name: bfblogweb1013
twcc_dbserver_name: bfblogdb1013
twcc_lb_name: bfbloglb1013
twcc_dbroot_pw: 1qaz2wsx
twcc_db_wordpress_id: wordpress
twcc_db_wordpress_pw: wordpresspw
