---
twcc_credential: "~/.twcc_data/credential"
allow_http_cidr: 0.0.0.0/0 # NOTE: keep this will be DANGEROUS!! http protocol is not suggested!
twcc_key: tempkey
# twcc_key_path: ./tempkey.pem
twcc_api_key: XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
twcc_project_id: ABC123456
twcc_webserver_name: bfblogweb1027
twcc_dbserver_name: bfblogdb1027
twcc_lb_name: bfbloglb1027
twcc_dbroot_pw: 1qaz2wsx
twcc_db_wordpress_id: wordpress
twcc_db_wordpress_pw: wordpresspw
